version: '3.5'
services:
  webapp:
    build:
      context: .
    ports:
      - '8082:80'
#    volumes:
#      - .:/webapp
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - /var/lib/mysql
